name: JSON checks

on:
  push:
    branches:
      - master
    paths:
      - '**.json'
  pull_request:
    paths:
      - '**.json'

jobs:
  syntax:
    name: Validate JSON syntax
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: json-syntax-check
        uses: limitusus/json-syntax-check@v2
        with:
          pattern: "\\.json$"
  schema:
    name: Validate JSON schema
    runs-on: ubuntu-20.04
    needs: syntax
    steps:
      - uses: actions/checkout@v3
      - name: install-deps
        run: pip3 install check-jsonschema
      - name: check-json-schema
        run: check-jsonschema --schemafile sopel_waifu/waifu.json.schema sopel_waifu/waifu.json
