name: JSON checks

on:
  push:
    branches:
      - master
    paths:
      - '**.json'
      - '**.json5'
      - '.github/workflows/json-checks.yml'
  pull_request:
    paths:
      - '**.json'
      - '**.json5'
      - '.github/workflows/json-checks.yml'

jobs:
  schema-lint:
    name: Lint/Validate JSON
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: install-deps
        run: make json5-lint-deps
      - name: check-keys
        run: make duplicates
      - name: check-json-schema
        run: make schema-check
  whitespace:
    name: Check for whitespace errors
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: install-deps
        run: make whitespace-deps
      - name: check-whitespace
        run: make whitespace
